### ISSUE TITLE
Reaction-Chooser from ReFlar Reaction is being overlapped by choice-strings

### ISSUE THREAD

**Issue by Braintelligence** [ReFlar/polls#12]
![grafik](https://user-images.githubusercontent.com/6761196/38748550-bc123b92-3f4e-11e8-91d0-8ee86689690a.png)

😸

**Comment by KyrneDev** [comment]
Can you provide me with the following info:

Browser and version:
Other extensions installed:

**Comment by Braintelligence** [comment]
Happens both on Google Chrome Version 65.0.3325.181 and on Firefox 59.0.2 .

These are my extensions:
![grafik](https://user-images.githubusercontent.com/6761196/38748706-487bd1e2-3f4f-11e8-965a-dd3213b171c7.png)

**Comment by KyrneDev** [comment]
Thank you for that, I'm on vacation at the moment. I, or one of the other member will look into this and your other issues

**Comment by Braintelligence** [comment]
Thank you. FYI: For some reason I can't edit polls as well. When I add another option it says "Oops, something went wrong." in the toast message ☹️
