### ISSUE TITLE
Can't vote with Firefox

### ISSUE THREAD

**Issue by Braintelligence** [ReFlar/polls#15]
When voting with Firefox I get a "Oops something went wrong" toast message.
Voting with Chrome works.
Refreshing the page in Firefox shows my vote afterwards.

Anyone else encountering this?

**Comment by Ralkage** [comment]
Confirmed that this is FireFox related (even developer edition is affected).

**Comment by KyrneDev** [comment]
Ah fun! Haven't ready delt with a million Firefox issues already. I'll take a look today

**Comment by Ralkage** [comment]
@CDK2020 I was able to reproduce and debug in Firefox Developer Edition long enough to see the error:

When editing a poll:

![image](https://user-images.githubusercontent.com/2059356/39099459-84a9f512-4649-11e8-8db8-73e58e4209e6.png)

When choosing a poll option to vote on:

![image](https://user-images.githubusercontent.com/2059356/39099464-9310f812-4649-11e8-90d0-4e806f54aaaa.png)

Hope this helps.

**Comment by KyrneDev** [comment]
Super helpful, I wasn't able to keep it around long enough to grab the error, thanks!
