### ISSUE TITLE
Gameplan: Current State of Extension

### ISSUE THREAD

**Issue by Ralkage** [ReFlar/polls#16]
It seems as if the latest version of this release has a lot of bugs, possibly more front-end if anything.

Bugs I've noticed myself:

* The following bugs seem to be specific to Firefox browser users (such as myself):
	* Currently unable to edit a poll successfully.
	* Currently unable to vote on poll options successfully.
* The following bugs are not browser specific:
	* When reaching the maximum amount of poll options you can add (10 currently), then decide to remove one (after reaching the maximum amount of options), you become unable to add more poll options even when the maximum is no longer reached.
	* Lots of type coercion's in the front-end where != should be !== and == should be === (a good example would be PollModal.js)
	* Lots of unused components/imports in the front-end (these cause clutter and are unnecessary to keep around if they are not being used).
	* Some parameters aren't being used at all (such as "number" in the choicePlaceholder() method/function).

Let me know if you need any help trying to fix some of these issues (I've been digging into some for about an hour now)

**Comment by KyrneDev** [comment]
See #17
