### ISSUE TITLE
Requesting Enchancement: Doodle Mode

### ISSUE THREAD

**Issue by webagil-kevin** [ReFlar/polls#2]
I sugest you to create a checkbox in edit pool for option  **"doodle mode"**:

* None, one or more possible answers
* Displays the answers of each participant as soon as the question

![Doodle](https://www.sebcar.net/wp-content/uploads/2013/03/doodle-calendrier-choix.jpg)

**Comment by Ralkage** [comment]
@CDK2020 what do you think about this enhancement/feature? I'm not sure if this will fit into the scope of this extension.

More notably, this fits within the lines of allowing multiple poll options to be voted on and or be changed.

**Comment by KyrneDev** [comment]
@Ralkage I feel like this isn't necessary because it's a forum and they can just make a post. @Shahiem throughts?

**Comment by Shahiem** [comment]
I think the same, it's not really necessary for a forum

**Comment by KyrneDev** [comment]
Alright, I think I'm going to close this then, if anyone had any objections, feel free to reopen it
