### ISSUE TITLE
Add a nice "slide in" animation on load

### ISSUE THREAD

**Issue by KyrneDev** [ReFlar/polls#22]
The poll bar should "load" up to its width

**Comment by dsevillamartin** [comment]
How fast do you want it to be?

**EDIT:** One second, ease-out:
![2018-04-26 19-54-52](https://user-images.githubusercontent.com/6401250/39337596-d104eada-498b-11e8-9382-1f71781d4039.gif)

**Comment by KyrneDev** [comment]
Satisfying, a nice ease in and out. 

I drafted `cubic-bezier(0.22, 0.045, 0.355, 1)`

**Comment by dsevillamartin** [comment]
I used keyframes for that demo. Is that ok? Never knew about cubic-bezier until now.
Flarum uses keyframes for fade in.
Also, I'll push to the Fixes branch cuz that's what I'm working from, and merge conflicts are dumb.

**Comment by KyrneDev** [comment]
Yup that's fine, just make it smooth, make sure it works if there are more than 1 answer. You were fast so let's include it in beta 1

**Comment by KyrneDev** [comment]
40b2101 closes
