### ISSUE TITLE
Update Files to Complete Extension Migration

### ISSUE THREAD

**Issue by Ralkage** [ReFlar/polls#4]
@Shahiem this is a to-do list we can all work on with you as far as completing the migration to ReFlar goes for this extension:

**Needs to meet ReFlar styling and standards:**

- [x] Update composer.json
- [x] Update namespaces.
- [x] Update packagist information.
- [x] Update README.md.
- [x] Assess database constraints due to migration issues.

**Comment by dsevillamartin** [comment]
I think #6 finishes this up.

**Comment by KyrneDev** [comment]
Packagist is the last thing we need

**Comment by dsevillamartin** [comment]
IMO should update packaging when new version rolls out

**Comment by ch-lopez** [comment]
@Shahiem can you give us permissions to edit for https://packagist.org/packages/treefiction/polls ?

**Comment by Ralkage** [comment]
@Shahiem can you give us permissions to edit for https://packagist.org/packages/treefiction/polls ?

Add the following users (us):

datitisev, issyrocks12, and Ralkage

**Comment by Shahiem** [comment]
@Ralkage: Done :) You should have permission to edit now

**Comment by Ralkage** [comment]
https://packagist.org/packages/treefiction/polls is now deprecated and can now be found VIA https://packagist.org/packages/reflar/polls.

Need one more task done which Luceos mentioned on Discord.
@Shahiem will create a mutation to look for the old namespace in the migrations table and replace it with `reflar`.

**Comment by dsevillamartin** [comment]
I’ve set the suggestion replacement package for treefiction/polls to reflar/polls

**Comment by Ralkage** [comment]
@datitisev excellent 👏 👏 

@Shahiem is the last item on this list still an issue? I remember it was discussed with Luceos but I'm not sure if you solved that issue in a recent update.

**Comment by KyrneDev** [comment]
I finished this in #17, will be included in 1.0.0-beta.1
