### ISSUE TITLE
Possible Name Change for Polls Extension

### ISSUE THREAD

**Issue by Ralkage** [ReFlar/polls#5]
This issue will serve as a discussion thread.

@Shahiem what do you think about the possibility of adding a unique name for this extension?

I was thinking of calling it "ballots" which is a more unique and playful way of saying voting or polls.

If not, I do suggest renaming it to "polls" as it is more of a plural word due to the fact that more than one poll can be created on a forum.

What do you think?

**Comment by dsevillamartin** [comment]
The package name is indeed reflar/polls, and I think the repo was just called poll, singular, which I fixed yesterday.

Reopen if I’m wrong, sorry. Or if you still want to discuss the new name.
