### ISSUE TITLE
Add PermissionGrid Options for Polls

### ISSUE THREAD

**Issue by Ralkage** [ReFlar/polls#8]
In a future release, we would want to create some PermissionGrid options for polls so that the Administrator has control of what groups can view or actions they can perform.

**Read**
- [ ] View polls (maybe?)
- [ ] View poll results

**Create**
- [x] Start a poll

**Participate**
- [x] Allow poll voting
- [x] Allow self-poll editing

**Moderate**
- [x] Delete polls
- [x] Edit polls

If you have any suggestions on what names we should use or what permissions I missed, please discuss here.

**Comment by Shahiem** [comment]
The **Delete polls** and **Edit polls** permission are added for the new version
